[I 15:17:35.971 NotebookApp] JupyterLab beta preview extension loaded from /root/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 15:17:35.971 NotebookApp] JupyterLab application directory is /root/anaconda3/share/jupyter/lab
[I 15:17:35.980 NotebookApp] Serving notebooks from local directory: /opt/pedro_test
[I 15:17:35.980 NotebookApp] 0 active kernels
[I 15:17:35.980 NotebookApp] The Jupyter Notebook is running at:
[I 15:17:35.980 NotebookApp] http://0.0.0.0:8888/
[I 15:17:35.980 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:17:43.122 NotebookApp] Interrupted...
[I 15:17:43.123 NotebookApp] Shutting down 0 kernels
[I 15:17:59.892 NotebookApp] JupyterLab beta preview extension loaded from /root/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 15:17:59.892 NotebookApp] JupyterLab application directory is /root/anaconda3/share/jupyter/lab
[I 15:17:59.915 NotebookApp] Serving notebooks from local directory: /opt/pedro_test
[I 15:17:59.915 NotebookApp] 0 active kernels
[I 15:17:59.916 NotebookApp] The Jupyter Notebook is running at:
[I 15:17:59.916 NotebookApp] http://0.0.0.0:8888/
[I 15:17:59.916 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:18:01.975 NotebookApp] Could not determine jupyterlab build status without nodejs
[I 15:18:03.840 NotebookApp] Kernel started: 1186721a-f114-4f68-bd58-f0c20d92777c
[I 15:18:05.824 NotebookApp] Adapting to protocol v5.1 for kernel 1186721a-f114-4f68-bd58-f0c20d92777c
[I 15:18:05.903 NotebookApp] Adapting to protocol v5.1 for kernel 1186721a-f114-4f68-bd58-f0c20d92777c
[I 15:21:20.354 NotebookApp] Interrupted...
[I 15:21:20.355 NotebookApp] Shutting down 1 kernel
Traceback (most recent call last):
  File "/root/anaconda3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/root/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1641, in start
    self.cleanup_kernels()
  File "/root/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1523, in cleanup_kernels
    self.kernel_manager.shutdown_all()
  File "/root/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 160, in shutdown_all
    self.finish_shutdown(kid)
  File "/root/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 33, in wrapped
    r = method(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 281, in finish_shutdown
    time.sleep(pollinterval)
KeyboardInterrupt
[I 15:21:26.742 NotebookApp] JupyterLab beta preview extension loaded from /root/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 15:21:26.743 NotebookApp] JupyterLab application directory is /root/anaconda3/share/jupyter/lab
[I 15:21:26.751 NotebookApp] Serving notebooks from local directory: /opt/pedro_test
[I 15:21:26.751 NotebookApp] 0 active kernels
[I 15:21:26.751 NotebookApp] The Jupyter Notebook is running at:
[I 15:21:26.751 NotebookApp] http://0.0.0.0:8888/
[I 15:21:26.751 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:21:27.775 NotebookApp] 404 GET /api/kernels/1186721a-f114-4f68-bd58-f0c20d92777c/channels?session_id=a33eca70a88b1b7bc7df9e26a9bd5262 (192.168.101.21): Kernel does not exist: 1186721a-f114-4f68-bd58-f0c20d92777c
[W 15:21:27.858 NotebookApp] 404 GET /api/kernels/1186721a-f114-4f68-bd58-f0c20d92777c/channels?session_id=a33eca70a88b1b7bc7df9e26a9bd5262 (192.168.101.21) 107.88ms referer=None
[W 15:21:34.162 NotebookApp] Could not determine jupyterlab build status without nodejs
[I 15:21:36.060 NotebookApp] Kernel started: b6df34b7-a33d-4795-b362-6513d1d46ccc
[I 15:21:36.072 NotebookApp] 302 GET / (192.168.101.21) 0.96ms
[I 15:21:37.463 NotebookApp] Adapting to protocol v5.1 for kernel b6df34b7-a33d-4795-b362-6513d1d46ccc
[I 15:22:42.054 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel b6df34b7-a33d-4795-b362-6513d1d46ccc restarted
[E 15:22:42.056 NotebookApp] KernelRestarter: restart callback <bound method ZMQChannelsHandler.on_kernel_restarted of ZMQChannelsHandler(b6df34b7-a33d-4795-b362-6513d1d46ccc)> failed
    Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.6/site-packages/jupyter_client/restarter.py", line 86, in _fire_callbacks
        callback()
      File "/root/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 466, in on_kernel_restarted
        self._send_status_message('restarting')
      File "/root/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 462, in _send_status_message
        self.write_message(json.dumps(msg, default=date_default))
      File "/root/anaconda3/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 15:22:44.330 NotebookApp] zmq message arrived on closed channel
[C 15:27:04.149 NotebookApp] received signal 15, stopping
[I 15:27:04.152 NotebookApp] Shutting down 1 kernel
[I 15:27:04.555 NotebookApp] Kernel shutdown: b6df34b7-a33d-4795-b362-6513d1d46ccc
